### ISSUE TITLE
Request for line numbers being displayed during editing

### ISSUE THREAD

**Issue by Devoth** [lindseydiloreto/craft-codeblock#1]
Hi lindseydiloreto!

What a nice plugin. I'm using it with Prism + Prism Line Highlight plugin on the front-end. To add support for highlighting lines I combined Code Block field with a simple plain text field to hold line numbers that should be highlighted. The only issue I have is that I have to manually count lines. It would be nice if Code Block had line numbers displayed, so only a quick glance would be needed to identify line numbers which need to be highlighted.

Anyways, great job with the plugin!

Cheers

**Comment by lindseydiloreto** [comment]
Hi @Devoth, thanks for the feedback! :)

Code Block is a pretty simple implementation... partly by design, and partly because there are other plugins which do a better job with more complex code snippets. Depending on what you're going for, I may recommend checking out one of those instead.

Not sure if you've seen it, but I highly recommend checking out Ace Freely for your needs!

>https://github.com/httpster/Ace-Freely
